# fly.toml app configuration file generated for backend-task-management-blue-star-5788 on 2024-09-02T12:09:07-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-task-management-blue-star-5788'
primary_region = 'gru'

[build]
  image = 'mysql:8'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = """--datadir /data/mysql \
    --default-authentication-plugin mysql_native_password"""

[env]
  MYSQL_DATABASE = ""
  MYSQL_USER = "non_root_user"
